// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signal.proto

#include "signal.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_company_2eproto ::google::protobuf::internal::SCCInfo<5> scc_info_Company_company_2eproto;
namespace YellowPages {
class SignalDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Signal> _instance;
} _Signal_default_instance_;
}  // namespace YellowPages
static void InitDefaultsSignal_signal_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::YellowPages::_Signal_default_instance_;
    new (ptr) ::YellowPages::Signal();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::YellowPages::Signal::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Signal_signal_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSignal_signal_2eproto}, {
      &scc_info_Company_company_2eproto.base,}};

void InitDefaults_signal_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_Signal_signal_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_signal_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_signal_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_signal_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_signal_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::YellowPages::Signal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::YellowPages::Signal, provider_id_),
  PROTOBUF_FIELD_OFFSET(::YellowPages::Signal, update_date_),
  PROTOBUF_FIELD_OFFSET(::YellowPages::Signal, company_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::YellowPages::Signal)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::YellowPages::_Signal_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_signal_2eproto = {
  {}, AddDescriptors_signal_2eproto, "signal.proto", schemas,
  file_default_instances, TableStruct_signal_2eproto::offsets,
  file_level_metadata_signal_2eproto, 1, file_level_enum_descriptors_signal_2eproto, file_level_service_descriptors_signal_2eproto,
};

const char descriptor_table_protodef_signal_2eproto[] =
  "\n\014signal.proto\022\013YellowPages\032\rcompany.pro"
  "to\"Y\n\006Signal\022\023\n\013provider_id\030\001 \001(\004\022\023\n\013upd"
  "ate_date\030\002 \001(\004\022%\n\007company\030\003 \001(\0132\024.Yellow"
  "Pages.Companyb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_signal_2eproto = {
  false, InitDefaults_signal_2eproto, 
  descriptor_table_protodef_signal_2eproto,
  "signal.proto", &assign_descriptors_table_signal_2eproto, 141,
};

void AddDescriptors_signal_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_company_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_signal_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_signal_2eproto = []() { AddDescriptors_signal_2eproto(); return true; }();
namespace YellowPages {

// ===================================================================

void Signal::InitAsDefaultInstance() {
  ::YellowPages::_Signal_default_instance_._instance.get_mutable()->company_ = const_cast< ::YellowPages::Company*>(
      ::YellowPages::Company::internal_default_instance());
}
class Signal::HasBitSetters {
 public:
  static const ::YellowPages::Company& company(const Signal* msg);
};

const ::YellowPages::Company&
Signal::HasBitSetters::company(const Signal* msg) {
  return *msg->company_;
}
void Signal::clear_company() {
  if (GetArenaNoVirtual() == nullptr && company_ != nullptr) {
    delete company_;
  }
  company_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Signal::kProviderIdFieldNumber;
const int Signal::kUpdateDateFieldNumber;
const int Signal::kCompanyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Signal::Signal()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:YellowPages.Signal)
}
Signal::Signal(const Signal& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_company()) {
    company_ = new ::YellowPages::Company(*from.company_);
  } else {
    company_ = nullptr;
  }
  ::memcpy(&provider_id_, &from.provider_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&update_date_) -
    reinterpret_cast<char*>(&provider_id_)) + sizeof(update_date_));
  // @@protoc_insertion_point(copy_constructor:YellowPages.Signal)
}

void Signal::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Signal_signal_2eproto.base);
  ::memset(&company_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_date_) -
      reinterpret_cast<char*>(&company_)) + sizeof(update_date_));
}

Signal::~Signal() {
  // @@protoc_insertion_point(destructor:YellowPages.Signal)
  SharedDtor();
}

void Signal::SharedDtor() {
  if (this != internal_default_instance()) delete company_;
}

void Signal::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Signal& Signal::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Signal_signal_2eproto.base);
  return *internal_default_instance();
}


void Signal::Clear() {
// @@protoc_insertion_point(message_clear_start:YellowPages.Signal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && company_ != nullptr) {
    delete company_;
  }
  company_ = nullptr;
  ::memset(&provider_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_date_) -
      reinterpret_cast<char*>(&provider_id_)) + sizeof(update_date_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Signal::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Signal*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint64 provider_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_provider_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint64 update_date = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_update_date(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .YellowPages.Company company = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::YellowPages::Company::_InternalParse;
        object = msg->mutable_company();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Signal::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:YellowPages.Signal)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 provider_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &provider_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 update_date = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &update_date_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .YellowPages.Company company = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_company()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:YellowPages.Signal)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:YellowPages.Signal)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Signal::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:YellowPages.Signal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 provider_id = 1;
  if (this->provider_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->provider_id(), output);
  }

  // uint64 update_date = 2;
  if (this->update_date() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->update_date(), output);
  }

  // .YellowPages.Company company = 3;
  if (this->has_company()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::company(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:YellowPages.Signal)
}

::google::protobuf::uint8* Signal::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:YellowPages.Signal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 provider_id = 1;
  if (this->provider_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->provider_id(), target);
  }

  // uint64 update_date = 2;
  if (this->update_date() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->update_date(), target);
  }

  // .YellowPages.Company company = 3;
  if (this->has_company()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::company(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:YellowPages.Signal)
  return target;
}

size_t Signal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:YellowPages.Signal)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .YellowPages.Company company = 3;
  if (this->has_company()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *company_);
  }

  // uint64 provider_id = 1;
  if (this->provider_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->provider_id());
  }

  // uint64 update_date = 2;
  if (this->update_date() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->update_date());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Signal::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:YellowPages.Signal)
  GOOGLE_DCHECK_NE(&from, this);
  const Signal* source =
      ::google::protobuf::DynamicCastToGenerated<Signal>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:YellowPages.Signal)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:YellowPages.Signal)
    MergeFrom(*source);
  }
}

void Signal::MergeFrom(const Signal& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:YellowPages.Signal)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_company()) {
    mutable_company()->::YellowPages::Company::MergeFrom(from.company());
  }
  if (from.provider_id() != 0) {
    set_provider_id(from.provider_id());
  }
  if (from.update_date() != 0) {
    set_update_date(from.update_date());
  }
}

void Signal::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:YellowPages.Signal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Signal::CopyFrom(const Signal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:YellowPages.Signal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Signal::IsInitialized() const {
  return true;
}

void Signal::Swap(Signal* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Signal::InternalSwap(Signal* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(company_, other->company_);
  swap(provider_id_, other->provider_id_);
  swap(update_date_, other->update_date_);
}

::google::protobuf::Metadata Signal::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_signal_2eproto);
  return ::file_level_metadata_signal_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace YellowPages
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::YellowPages::Signal* Arena::CreateMaybeMessage< ::YellowPages::Signal >(Arena* arena) {
  return Arena::CreateInternal< ::YellowPages::Signal >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
