// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_catalog.proto

#include "transport_catalog.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_database_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Database_database_2eproto;
namespace ProtoTransport {
class TransportCatalogDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TransportCatalog> _instance;
} _TransportCatalog_default_instance_;
}  // namespace ProtoTransport
static void InitDefaultsTransportCatalog_transport_5fcatalog_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ProtoTransport::_TransportCatalog_default_instance_;
    new (ptr) ::ProtoTransport::TransportCatalog();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtoTransport::TransportCatalog::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TransportCatalog_transport_5fcatalog_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTransportCatalog_transport_5fcatalog_2eproto}, {
      &scc_info_Database_database_2eproto.base,}};

void InitDefaults_transport_5fcatalog_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_TransportCatalog_transport_5fcatalog_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_transport_5fcatalog_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_transport_5fcatalog_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_transport_5fcatalog_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_transport_5fcatalog_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoTransport::TransportCatalog, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ProtoTransport::TransportCatalog, db_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ProtoTransport::TransportCatalog)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ProtoTransport::_TransportCatalog_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_transport_5fcatalog_2eproto = {
  {}, AddDescriptors_transport_5fcatalog_2eproto, "transport_catalog.proto", schemas,
  file_default_instances, TableStruct_transport_5fcatalog_2eproto::offsets,
  file_level_metadata_transport_5fcatalog_2eproto, 1, file_level_enum_descriptors_transport_5fcatalog_2eproto, file_level_service_descriptors_transport_5fcatalog_2eproto,
};

const char descriptor_table_protodef_transport_5fcatalog_2eproto[] =
  "\n\027transport_catalog.proto\022\016ProtoTranspor"
  "t\032\016database.proto\"8\n\020TransportCatalog\022$\n"
  "\002db\030\001 \001(\0132\030.ProtoTransport.Databaseb\006pro"
  "to3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_transport_5fcatalog_2eproto = {
  false, InitDefaults_transport_5fcatalog_2eproto, 
  descriptor_table_protodef_transport_5fcatalog_2eproto,
  "transport_catalog.proto", &assign_descriptors_table_transport_5fcatalog_2eproto, 123,
};

void AddDescriptors_transport_5fcatalog_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_database_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_transport_5fcatalog_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_transport_5fcatalog_2eproto = []() { AddDescriptors_transport_5fcatalog_2eproto(); return true; }();
namespace ProtoTransport {

// ===================================================================

void TransportCatalog::InitAsDefaultInstance() {
  ::ProtoTransport::_TransportCatalog_default_instance_._instance.get_mutable()->db_ = const_cast< ::ProtoTransport::Database*>(
      ::ProtoTransport::Database::internal_default_instance());
}
class TransportCatalog::HasBitSetters {
 public:
  static const ::ProtoTransport::Database& db(const TransportCatalog* msg);
};

const ::ProtoTransport::Database&
TransportCatalog::HasBitSetters::db(const TransportCatalog* msg) {
  return *msg->db_;
}
void TransportCatalog::clear_db() {
  if (GetArenaNoVirtual() == nullptr && db_ != nullptr) {
    delete db_;
  }
  db_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TransportCatalog::kDbFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TransportCatalog::TransportCatalog()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtoTransport.TransportCatalog)
}
TransportCatalog::TransportCatalog(const TransportCatalog& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_db()) {
    db_ = new ::ProtoTransport::Database(*from.db_);
  } else {
    db_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:ProtoTransport.TransportCatalog)
}

void TransportCatalog::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_TransportCatalog_transport_5fcatalog_2eproto.base);
  db_ = nullptr;
}

TransportCatalog::~TransportCatalog() {
  // @@protoc_insertion_point(destructor:ProtoTransport.TransportCatalog)
  SharedDtor();
}

void TransportCatalog::SharedDtor() {
  if (this != internal_default_instance()) delete db_;
}

void TransportCatalog::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TransportCatalog& TransportCatalog::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TransportCatalog_transport_5fcatalog_2eproto.base);
  return *internal_default_instance();
}


void TransportCatalog::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoTransport.TransportCatalog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && db_ != nullptr) {
    delete db_;
  }
  db_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TransportCatalog::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TransportCatalog*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .ProtoTransport.Database db = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::ProtoTransport::Database::_InternalParse;
        object = msg->mutable_db();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TransportCatalog::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtoTransport.TransportCatalog)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .ProtoTransport.Database db = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_db()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtoTransport.TransportCatalog)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtoTransport.TransportCatalog)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TransportCatalog::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtoTransport.TransportCatalog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ProtoTransport.Database db = 1;
  if (this->has_db()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::db(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtoTransport.TransportCatalog)
}

::google::protobuf::uint8* TransportCatalog::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtoTransport.TransportCatalog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ProtoTransport.Database db = 1;
  if (this->has_db()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::db(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoTransport.TransportCatalog)
  return target;
}

size_t TransportCatalog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoTransport.TransportCatalog)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ProtoTransport.Database db = 1;
  if (this->has_db()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *db_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TransportCatalog::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtoTransport.TransportCatalog)
  GOOGLE_DCHECK_NE(&from, this);
  const TransportCatalog* source =
      ::google::protobuf::DynamicCastToGenerated<TransportCatalog>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtoTransport.TransportCatalog)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtoTransport.TransportCatalog)
    MergeFrom(*source);
  }
}

void TransportCatalog::MergeFrom(const TransportCatalog& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoTransport.TransportCatalog)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_db()) {
    mutable_db()->::ProtoTransport::Database::MergeFrom(from.db());
  }
}

void TransportCatalog::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtoTransport.TransportCatalog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransportCatalog::CopyFrom(const TransportCatalog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoTransport.TransportCatalog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransportCatalog::IsInitialized() const {
  return true;
}

void TransportCatalog::Swap(TransportCatalog* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TransportCatalog::InternalSwap(TransportCatalog* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(db_, other->db_);
}

::google::protobuf::Metadata TransportCatalog::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_transport_5fcatalog_2eproto);
  return ::file_level_metadata_transport_5fcatalog_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtoTransport
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::ProtoTransport::TransportCatalog* Arena::CreateMaybeMessage< ::ProtoTransport::TransportCatalog >(Arena* arena) {
  return Arena::CreateInternal< ::ProtoTransport::TransportCatalog >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
